services:
  aiproxy:
    image: aiproxy:latest
    container_name: aiproxy
    build:
      context: .
    ports:
      - "3100:3100"
    env_file:
      - app/.env
    environment:
      - PROXY_PORT=3100
      - PROXY_STORAGE_DIR=/home/data
    volumes:
      - ./data:/home/data
